
server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fiap-database
    username: dev
    password: fiap
  jpa:
    hibernate.ddl-auto: update
    show-sql: true